pipeline {
    agent any
    parameters {
        string(name: 'DOCKER_TAG', description: 'Tag de la imagen Docker', defaultValue: 'latest')
    }
    environment {
        DOCKER_USER_CRED = credentials('alex-joaquin-dockerhub')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'sonarqube_5.0'
                    withSonarQubeEnv(installationName: 'aroldev sonarqube') {
                        sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=alex-project-kubecamp-go -Dsonar.sources=./services/go-auth -Dsonar.exclusions=**/*_test.go -Dsonar.tests=./services/go-auth -Dsonar.test.inclusions=**/*_test.go"
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('services/go-auth'){
                    script {
                        // def dockerfile = 'Dockerfile.test'
                        // testContainer = docker.build("aalleexx98/alex-project-kubecamp-go:testing", "-f $dockerfile .")
                        // testContainer.run()
                         // Utiliza Docker Compose para construir e iniciar contenedores
                        sh "docker-compose -f docker-compose.t.yaml up -d"

                        // Obtiene el nombre del contenedor Go
                        def goContainerName = sh(script: "docker-compose -f docker-compose.t.yaml ps -q app-test", returnStdout: true).trim()

                        // Ejecuta los comandos de prueba dentro del contenedor Go
                        def command = 'go test ./...'
                        def exitCode = sh(script: "docker exec -i $goContainerName $command", returnStatus: true)

                        // Detén y elimina los contenedores de Docker Compose
                        sh "docker-compose -f docker-compose.t.yaml down"

                        if (exitCode != 0) {
                            currentBuild.result = 'FAILED'
                        }
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def dockerTag = params.DOCKER_TAG
                    def dockerfile = 'services/go-auth/Dockerfile'
                    sh "docker build -t aalleexx98/alex-project-kubecamp-go:$dockerTag -f $dockerfile ."
                    // Mirar lo del dir.
                }
            }
        }

        stage('Loggin in docker hub'){
            steps {
                sh "docker login -u $DOCKER_USER_CRED_USR -p $DOCKER_USER_CRED_PSW"
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    def dockerTag = params.DOCKER_TAG
                    sh "docker push aalleexx98/alex-project-kubecamp-go:$dockerTag"
                }
            }
        }

        stage('Cleanup') {
            steps {
                script {
                    // Detener y eliminar el contenedor de prueba
                    testContainer.stop()
                    testContainer.remove()
                }
            }
        }
     }
}