apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-go-auth-service
spec:
  selector:
    app: go-auth
  ports:
    - protocol: TCP
      port: {{ .Values.goAuth.port }}
      targetPort: {{ .Values.goAuth.port }}
